apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # External port
      targetPort: 80  # Internal container port
  selector:
    app: frontend