apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: 992382821771.dkr.ecr.us-east-2.amazonaws.com/primer-designer-front-end:latest
        ports:
        - containerPort: 80