name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - testing

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Amazon ECR
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws configure set default.region $AWS_REGION
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.$AWS_REGION.amazonaws.com

    - name: Build, tag, and push Docker image to ECR
      env:
        ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        ECR_REPOSITORY: bioinfo/primer-designer-front-end
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update task definition with new image
      id: task-def
      run: |
        sed -i 's|<IMAGE_URI>|${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/bioinfo/primer-designer-front-end:${{ github.sha }}|' .github/workflows/ecs-task-definition.json
        echo "::set-output name=task-def::$(cat .github/workflows/ecs-task-definition.json)"

    - name: Deploy to ECS (Testing)
      if: github.ref == 'refs/heads/testing'
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: .github/workflows/ecs-task-definition.json
        service: primer-designer-front-end-test-service
        cluster: bioinfo_cluster
        wait-for-service-stability: true

    - name: Deploy to ECS (Production)
      if: github.ref == 'refs/heads/main'
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: .github/workflows/ecs-task-definition.json
        service: primer-designer-front-end-production-service
        cluster: bioinfo_cluster
        wait-for-service-stability: true